<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
	$config['protocol'] = 'smtp';
	$config['smtp_host'] = 'ssl://smtp.gmail.com'; 
	$config['smtp_port'] = '465';
	$config['smtp_user'] = 'testappastana@gmail.com'; 
	$config['smtp_pass'] = '2015qwerty';
	$config['mailtype'] = 'html';
	$config['charset'] = 'utf-8';
	$config['wordwrap'] = TRUE;
	$config['newline'] = "\r\n"; 